[pytest]
asyncio_mode = strict
asyncio_default_fixture_scope = function
testpaths = tests
python_files = *_spec.py test_*.py
markers =
    asyncio: mark test as asyncio
    e2e: mark test as E2E (integration)
